### ISSUE TITLE
کتاب Python Tricks

### ISSUE THREAD

**Issue by mthri** [mashhadlug/book-summary#3]
سلام، من این کتاب رو مطالعه کردم، خوب بود ولی فکر نکنم توی یکی دوساعت جمع بشه  
حالا پیشنهاد شما چی هست؟ 
نظر خودم روی رکورد ویدیو برای هرفصل باشه(ترجیحا کوتاه) و انشار اون به اسم لاگ

**Comment by ohmydevops** [comment]
<div dir='rtl'>

سلام امیرجان
هر کتاب میتونه حداکثر یک جلسه بهش اختصاص پیدا کنه (چون اگر سریالی بشه جلسات برای یک کتاب، خیلی فاصله میفته بین کتاب‌های مختلف)
هدف این نیست که همه کتاب رو مطرح کنیم، فقط یک دید کلی درباره کتاب و بخش‌های جالب‌تر و مهم‌ترشو مرور کردن و همین چیزا. در نهایت بعد از جلسه خروجیش این میشه که هم یک سری چیز جالب و کوچیک یاد میگیریم و هم در نهایت افرادی که علاقه دارند به این موضوعات میفهمن که کتاب براشون مفیده یا نه.

</div>

**Comment by mthri** [comment]
اوکی
ببین اگر کتابش خوب هست، بزار تو نوبت

**Comment by ohmydevops** [comment]
عالیه. حتما. اضافه کردم

**Comment by ohmydevops** [comment]
سلام امیر جان. شما برای این کتاب چه زمانی مد نظرته؟

**Comment by mthri** [comment]
سلام
هفته اول تیرماه خوب هست؟

**Comment by ohmydevops** [comment]
من که اکیم. برای خودت هر وقت خوب بود بگو.حالا برای روز و ساعت هم برنامه‌ریزی میکنیم

**Comment by mthri** [comment]
برای سوم تیر فعلا

**Comment by ohmydevops** [comment]
<div dir='rtl'>
طبق صحبتمون پس شما شدی هفته بعد از من، یعنی ۱۰ تیر، ولی خب درباره زمانش طبق برنامه‌ خودت و فیکس شدن زمان جلسات کتاب‌خوانی مجدد هماهنگی و برنامه‌ریزی میکنیم

</div>

**Comment by ohmydevops** [comment]
چهارشنبه ۹ تیر ۱۴۰۰ تصویب شد
